apiVersion: v1
kind: Service
metadata:
  name: traefik-apikeys-service
  namespace: traefik-apikeys
spec:
  selector:
    app: traefik-apikeys
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
