# use class=""
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-dev-pvc
  namespace: minio-dev
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: minio-dev-pv
