# use class=""
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jsonllm-pvc
  namespace: jsonllm
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: jsonllm-pv
