apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    KEYCLOAK_ADMIN: AgDibP5UIUzzMgE607RnPjo6ThXsOIezGsbDBBJjhQpVjSiMI+yoHXHbQayhAGepUL+EPB67GtPAaplYT42UiKt2cJQqlc3DOwZfzxiW49mrmVagIsuEj+hIggpNoZiZ672CNCsGfoMelZQW7s+6lSZY+lccRVWNxrwajZqLixa70XgFHZ231hSr1hyISHoa/Vu6Db7T7NAjhcgjvhvyP5hvyBlmakdKU87k/iC4ult10ljD71cY9P05iFFcdD18dkSqVn1Qe0IeLN89u+9xy1A8UdB8adC8KGb0WGTBl/9ztfqPODWDHtgn9Kxg/YRnW0GxWRsOIgQj6ZVNh3lVMn8mfPOJ/QZxOEpxqmFa7eiTs6tcVKrit6sBir49B3Tub5SdSwLC9cremeKln+DJBWcQ0D6M7cdyqy4J8IZ3OepfggCReYPhwhySBm4Yjqf3F7xJReANtb9GRYRJXvYVoonUF85TY3M6B/3k4blxect2tDEIYccdMZ2jiKNYrajkFswiagP/brZfTZ7Oz0NBDi0ZgfCIGT7vKmUkisNIi6OUzIIIjSZjmw0TxffGYJaEDNTmJUNkvJ1OYGOnFqipKNAi096SdpEEh4kZveKl5nAZJie/Rqf/pSDDjg430ggqpslQHls1RD5S1wW5hJd2NatXFOxK6ap5lNZpeC0CC1CIAwgx5s5GOAAyK9DfrDUc2MHldlsAKXostQ==
    KEYCLOAK_ADMIN_PASSWORD: AgCInWWrQi71pw43u5xQSYr8iJbS7n6O5pDcCayZLhH8oTNw7uIktcEuRu6VGNdketScOLp5XlfBbM6hEZTfX+3BcFpqiuuYjn8Z+V3WfpKRPF+BzqWj7dfrJXxwdlDsRvZI9OeEfh+qGw34nQhpnRh7/R6KuPYaiHG/LldThDC5pkcnM39jLBdQOp2IRaP+Yk/ma0LXfxt+RMZ2t3H4f1jR4ih7RaaOR0wOP0r90PctgdgkwIon1vWwN3Olxs+RpGp+pnO0cJU5Sp/9D54PBbJLXRSgXl7SYnK0JW/6Khyt/+q45qrg6jD0DdswOaNLcNmRWrXv/ea/8xS3c1CojPGRv/bsCflFwc317W4g8qaymiRWLp9Gk2cwvC60/JbOCcSbsBlmr4jjmgm70SXiWb16NFzQN2qqtKcdCdXTVo99o+VB2NVJGtm7IslS6yCbox6EFTndswTQZtnpZ24LgGoBHXnVYfI8sJkOSiLobB0FdNSmPV5D4Pvm8QAkuPl/J1kdZW8O1SHkig0fP2WmGCz5cH6F1pzBMJb5veGCiu1EodPLFOi+ON2BP4dYtnZEUbFs68T3xI4Z+Bb4B1ROI7VgUSQ+Vma+qcu6DATj6v/uamDQSZmb5mpSBFFIKO8tzX3RhU/XP2HY1hRcf37j9Ju9oRGUyVJz80aPVdFwpDfG3HWrEfW3qlgiI/mJzwj8IvD7Q67SueBkfn/4
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin
      namespace: keycloak

